In [1]:
import pandas as pd
import numpy as np

viagra_spam = {'viagra':[1,0,0,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,1],
               'spam':[1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,1,1]}

d = pd.DataFrame(viagra_spam).values
d

array([[1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [1, 1]], dtype=int64)

In [2]:
#P(V)
pv = sum(d[:, 0]) / len(d)

#P(S)
ps = sum(d[:, 1]) / len(d)

#P(V&S)
pvs = sum((d[:, 0] == 1) & (d[:, 1] == 1)) / len(d)

#P(~V&S)
p_vs = sum((d[:, 0] == 0) & (d[:, 1] == 1)) / len(d)

pv, ps, pvs, p_vs

(0.3, 0.3, 0.15, 0.15)

In [3]:
#P(S|V)
#P(V&S) / P(V)
pvs/pv

0.5

In [4]:
#P(S|~V)
#P(~V&S) / P(~V)
#P(~V) = 1 - P(V)
p_vs / (1 - pv)

0.2142857142857143

In [5]:
import pandas as pd
import numpy as np

data_url = "./data/fraud.csv"
df= pd.read_csv(data_url) 
df.head()

,ID,History,CoApplicant,Accommodation,Fraud
0,1,current,none,own,True
1,2,paid,none,own,False
2,3,paid,none,own,False
3,4,paid,guarantor,rent,True
4,5,arrears,none,own,False


In [6]:
df.drop("ID", axis=1, inplace=True)

In [7]:
Y = df.pop("Fraud")
X = pd.get_dummies(df)

Y, X.T

(0      True
 1     False
 2     False
 3      True
 4     False
 5      True
 6     False
 7     False
 8     False
 9      True
 10    False
 11     True
 12     True
 13    False
 14    False
 15    False
 16    False
 17    False
 18    False
 19    False
 Name: Fraud, dtype: bool,
                             0      1      2      3      4      5      6   \
 History_arrears          False  False  False  False   True   True  False   
 History_current           True  False  False  False  False  False   True   
 History_none             False  False  False  False  False  False  False   
 History_paid             False   True   True   True  False  False  False   
 CoApplicant_coapplicant  False  False  False  False  False  False  False   
 CoApplicant_guarantor    False  False  False   True  False  False  False   
 CoApplicant_none          True   True   True  False   True   True   True   
 Accommodation_free       False  False  False  False  False  False  False   
 Accommodation_own  

In [8]:
X.head().T

,0,1,2,3,4
History_arrears,False,False,False,False,True
History_current,True,False,False,False,False
History_none,False,False,False,False,False
History_paid,False,True,True,True,False
CoApplicant_coapplicant,False,False,False,False,False
CoApplicant_guarantor,False,False,False,True,False
CoApplicant_none,True,True,True,False,True
Accommodation_free,False,False,False,False,False
Accommodation_own,True,True,True,False,True
Accommodation_rent,False,False,False,True,False


In [9]:
from sklearn.naive_bayes import BernoulliNB

bnb = BernoulliNB() # 객체 생성, 열 별로 확률 계산할 준비 완료
bnb.fit(X, Y) # 확률 구하기

BernoulliNB()

In [10]:
Y2 = bnb.predict(X) # predict_proba 예측 확률 출력

In [11]:
from sklearn.metrics import confusion_matrix

confusion_matrix(Y, Y2)

array([[13,  1],
       [ 4,  2]], dtype=int64)

In [12]:
text_example = [ "A great game game",
                "The team played a great game",
                "The match was exciting",
                "A clean game with great players",
                "The team won the match",
                "The player scored a goal",
                "It was a close game",
                "The championship match was amazing",
                "The team celebrated the victory",
                "A fantastic game by the players",
                "The election results were announced",
                "The election campaign was intense",
                "The president won the election",
                "The government announced new policy",
                "The parliament passed the law",
                "The political debate was heated",
                "The candidate started the campaign",
                "The voters supported the candidate",
                "The election vote counting began",
                "The government election strategy changed"]

y = ["sports","sports","sports","sports","sports",
    "sports","sports","sports","sports","sports",
    "politics","politics","politics","politics","politics",
    "politics","politics","politics","politics","politics"]

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
# 단어 종류 가져오기 + 개수 세기
temp = cv.fit_transform(text_example)
X = temp.toarray()

In [14]:
cv.get_feature_names_out()

array(['amazing', 'announced', 'began', 'by', 'campaign', 'candidate',
       'celebrated', 'championship', 'changed', 'clean', 'close',
       'counting', 'debate', 'election', 'exciting', 'fantastic', 'game',
       'goal', 'government', 'great', 'heated', 'intense', 'it', 'law',
       'match', 'new', 'parliament', 'passed', 'played', 'player',
       'players', 'policy', 'political', 'president', 'results', 'scored',
       'started', 'strategy', 'supported', 'team', 'the', 'victory',
       'vote', 'voters', 'was', 'were', 'with', 'won'], dtype=object)

In [15]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X, y)

MultinomialNB()

In [16]:
text = ["The Election is Coming"]
newText = cv.transform(text).toarray()
mnb.predict_proba(newText)

array([[0.89017096, 0.10982904]])

In [34]:
from sklearn import datasets #내장 데이터셋 사용
from sklearn.naive_bayes import GaussianNB
import pandas as pd

iris = datasets.load_iris()
X = iris.data
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [35]:
Y = iris.target
Y[:5]

array([0, 0, 0, 0, 0])

In [36]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [37]:
from sklearn.model_selection import train_test_split

trX, teX, trY, teY = train_test_split(X, Y, test_size=0.25)
trX.shape, teX.shape

((112, 4), (38, 4))

In [38]:
gnb = GaussianNB()
gnb.fit(trX, trY)

GaussianNB()

In [39]:
test = [[5.3, 4.2, 1.2, 2.3]]
idx = gnb.predict(test)
iris.target_names[idx]

array(['virginica'], dtype='<U10')

In [40]:
Y2 = gnb.predict(teX)
Y2[:5]

array([2, 2, 2, 2, 1])

In [43]:
gnb.predict_proba(teX)

array([[2.93777870e-280, 2.25144908e-014, 1.00000000e+000],
       [4.32844371e-130, 1.78065201e-001, 8.21934799e-001],
       [8.97315315e-217, 4.59819293e-008, 9.99999954e-001],
       [4.96177752e-150, 2.03054698e-002, 9.79694530e-001],
       [8.25982153e-071, 9.99859760e-001, 1.40239647e-004],
       [2.30670519e-216, 1.31305821e-008, 9.99999987e-001],
       [3.15470663e-030, 9.99999878e-001, 1.21736882e-007],
       [2.93880040e-197, 7.24416124e-008, 9.99999928e-001],
       [4.16946084e-110, 7.20547622e-001, 2.79452378e-001],
       [1.00000000e+000, 1.49033789e-019, 5.16921644e-026],
       [3.05725380e-096, 9.86030525e-001, 1.39694754e-002],
       [9.26253590e-111, 8.49508689e-001, 1.50491311e-001],
       [2.13755991e-143, 4.31935363e-002, 9.56806464e-001],
       [1.00000000e+000, 9.10802546e-016, 4.30309340e-022],
       [1.00000000e+000, 8.63627635e-020, 1.33493594e-025],
       [1.00000000e+000, 1.52908921e-019, 1.16858344e-025],
       [1.25047769e-094, 9.97899287e-001

In [44]:
confusion_matrix(teY, Y2)

array([[11,  0,  0],
       [ 0, 14,  2],
       [ 0,  1, 10]], dtype=int64)

In [45]:
from sklearn.metrics import classification_report
print(classification_report(teY, Y2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      0.88      0.90        16
           2       0.83      0.91      0.87        11

    accuracy                           0.92        38
   macro avg       0.92      0.93      0.92        38
weighted avg       0.92      0.92      0.92        38

