In [10]:
import numpy as np

X = np.array([[2.54, 4.33, 3.99, 2.57], # 환자 0
[3.12, 3.87, 3.84, 3.04], # 환자 1
[2.76, 4.17, 5.63, 3.28], # 환자 2
[3.87, 3.56, 4.25, 3.65], # 환자 3
[3.55, 3.91, 2.68, 4.22], # 환자 4
[4.12, 2.86, 3.30, 3.71]]) # 환자 5

labels = np.array(["정상", "정상", "정상", "확진", "확진", "확진"])

X

array([[2.54, 4.33, 3.99, 2.57],
       [3.12, 3.87, 3.84, 3.04],
       [2.76, 4.17, 5.63, 3.28],
       [3.87, 3.56, 4.25, 3.65],
       [3.55, 3.91, 2.68, 4.22],
       [4.12, 2.86, 3.3 , 3.71]])

In [11]:
new = np.array([[3.24, 3.68, 3.82, 3.77]])
new

array([[3.24, 3.68, 3.82, 3.77]])

In [18]:
dist = np.sum(np.sqrt((X - new)**2), axis=1)

In [23]:
who = dist.argmin() # 최솟값인 인덱스 반환

In [24]:
labels[who]

'정상'

In [25]:
from sklearn.neighbors import KNeighborsClassifier

knc = KNeighborsClassifier(n_neighbors=1)
knc.fit(X, labels) # 거리 계산하지 않음, 구조만 맞추고 매개변수 넣는 등 준비만 함

KNeighborsClassifier(n_neighbors=1)

In [26]:
knc.predict(new)

array(['정상'], dtype='<U2')

In [38]:
# k = 3
k = 3
temp = np.argsort(dist)
idx = temp[:k]
idx

array([1, 3, 4], dtype=int64)

In [48]:
pred = labels[idx]
pred

array(['정상', '확진', '확진'], dtype='<U2')

In [49]:
np.sum(labels[idx] == '정상')

1

In [50]:
np.sum(labels[idx] == '확진')

2

In [52]:
if(np.sum(pred == '확진') > np.sum(pred == '정상')): print('확진')
else: print('정상')

확진


In [53]:
from sklearn.neighbors import KNeighborsClassifier

knc = KNeighborsClassifier(n_neighbors=3)
knc.fit(X, labels) # 거리 계산하지 않음, 구조만 맞추고 매개변수 넣는 등 준비만 함

KNeighborsClassifier(n_neighbors=3)

In [54]:
knc.predict(new)

array(['확진'], dtype='<U2')

In [55]:
# 입력 데이터 (다른 과목 점수)
X = np.array([ [7.5, 7.5, 7.0, 9.5, 8.5],# 학생0
[7.5, 7.0, 7.5, 8.0, 8.0], # 학생1
[8.0, 7.0, 8.0, 8.0, 8.5], # 학생2
[8.5, 8.0, 9.5, 7.5, 6.0], # 학생3
[10.0, 9.5, 9.0, 7.5, 7.5], # 학생4
[9.0, 9.0, 8.0, 8.0, 8.0]]) # 학생5
# 정답 (인공지능 점수)
y = np.array([5.0, 6.0, 8.5, 7.0, 10.0, 9.0])
# 신입 학생
new = np.array([9.0, 8.5, 8.0, 7.0, 8.0])

In [61]:
dist = np.sqrt(np.sum((X - new)**2, axis=1))
dist

array([3.27871926, 2.39791576, 2.12132034, 2.64575131, 1.87082869,
       1.11803399])

In [63]:
idx = np.argsort(dist)
idx

array([5, 4, 2, 1, 3, 0], dtype=int64)

In [68]:
k = 3
y[idx[:k]]

array([ 9. , 10. ,  8.5])

In [69]:
np.mean(y[idx[:k]])

9.166666666666666

In [73]:
from sklearn.neighbors import KNeighborsRegressor
knr = KNeighborsRegressor(n_neighbors=k)
knr.fit(X, y) # 유클리드 거리 계산하지 않음, 준비만 함

KNeighborsRegressor(n_neighbors=3)

In [76]:
knr.predict([new])

array([9.16666667])

In [78]:
import pandas as pd

test = pd.read_csv("./data/basketball_test.csv")
train = pd.read_csv("./data/basketball_train.csv")

print(test.head())
print(train.head())

   Unnamed: 0           Player Pos   3P   TRB  BLK
0          96      Dwyane Wade  SG  0.8   4.5  0.7
1          39     Tim Hardaway  SG  1.9   2.8  0.2
2          21  Jordan Crawford  SG  1.9   1.8  0.1
3          95   Nikola Vucevic   C  0.3  10.4  1.0
4          56      Kyle Korver  SG  2.4   2.8  0.3
   Unnamed: 0           Player Pos   3P  TRB  BLK
0          26  Wayne Ellington  SG  2.4  2.1  0.1
1          86     Nik Stauskas  SG  1.7  2.8  0.4
2          60         Alex Len   C  0.0  6.6  1.3
3          45      Buddy Hield  SG  1.8  3.3  0.1
4          68      Jodie Meeks  SG  1.6  2.1  0.1


In [96]:
X_tr = train[["3P", "BLK"]].values # 값만 추출하여 넘파이 배열 객체로 변환
Y_tr = train["Pos"].values

X_te = test[["3P", "BLK"]].values
Y_te = test["Pos"].values

X_tr[:5], Y_tr[:5], X_te[:5], Y_te[:5] 

(array([[2.4, 0.1],
        [1.7, 0.4],
        [0. , 1.3],
        [1.8, 0.1],
        [1.6, 0.1]]),
 array(['SG', 'SG', 'C', 'SG', 'SG'], dtype=object),
 array([[0.8, 0.7],
        [1.9, 0.2],
        [1.9, 0.1],
        [0.3, 1. ],
        [2.4, 0.3]]),
 array(['SG', 'SG', 'SG', 'C', 'SG'], dtype=object))

In [98]:
X_tr.shape

(80, 2)

In [119]:
from sklearn.metrics import accuracy_score
k = 1 # 1 ~ 10까지 넘파이 배열 생성
k

1

In [132]:
scores = []

for k in range(1, 11):
    m = KNeighborsClassifier(n_neighbors=k)
    m.fit(X_tr, Y_tr) # 유클리드 거리 계산 하지 않음
    y_hat = m.predict(X_te)
    scores.append(accuracy_score(Y_te, y_hat))
scores

[0.8, 0.75, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]

In [133]:
np.argmax(scores)+1 # argmax: 큰 값 중에 가장 앞 쪽 인덱스 반환

3

In [135]:
k=3
m = KNeighborsClassifier(n_neighbors=k)
m.fit(X_tr, Y_tr) # 유클리드 거리 계산 하지 않음
y_hat = m.predict(X_te)

In [137]:
from sklearn.metrics import confusion_matrix # 실제값 먼저, 예측값 다음
from sklearn.metrics import classification_report

# m.classes_ : 분류한 클래스 이름 반환
# 0 : 'C'
# 1 : 'SG'
# [0, 0] : 실제값 'C'를 'C'로 예측
# [0, 1] : 실제값 'C'를 'SG'로 예측
# [1, 0] : 
# [1, 1] : 
confusion_matrix(Y_te, y_hat)

array([[ 6,  1],
       [ 1, 12]], dtype=int64)

In [138]:
m.classes_

array(['C', 'SG'], dtype=object)

In [139]:
print(classification_report(Y_te, y_hat))

              precision    recall  f1-score   support

           C       0.86      0.86      0.86         7
          SG       0.92      0.92      0.92        13

    accuracy                           0.90        20
   macro avg       0.89      0.89      0.89        20
weighted avg       0.90      0.90      0.90        20

